# Generated by Django 2.0.7 on 2018-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_group_name', models.CharField(max_length=100)),
                ('chat_log', models.TextField()),
            ],
        ),
    ]
